# Docs: https://github.com/netlify-labs/netlify-plugin-lighthouse#readme

[[plugins]]
   package = "@netlify/plugin-lighthouse"

   # optional, fails build when a category is below a threshold
   [plugins.inputs.thresholds]
      performance = 0.9
      accessibility = 0.9
      best-practices = 0.9
      seo = 0.9

   # to audit a sub path of the build directory
   # route1 audit will use the top level thresholds
   [[plugins.inputs.audits]]
      path = "/portfolio/moonrise"

      # you can specify output_path per audit, relative to the path
      output_path = "reports/route1.html"

