# Docs: https://github.com/netlify-labs/netlify-plugin-lighthouse#readme

[[plugins]]
   package = "@netlify/plugin-lighthouse"

   # optional, fails build when a category is below a threshold
   [plugins.inputs.thresholds]
      performance = 0.8
      accessibility = 0.8
      best-practices = 0.8
      seo = 0.8


  package = "netlify-plugin-cloudinary"

  [plugins.inputs]
  imagesPath = "/src/client-work/images"