# Docs: https://www.foo.software/docs/lighthouse-check-github-action/configuration

name: Lighthouse Audit on Netlify Preview
on: [pull_request]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Lighthouse
      uses: foo-software/lighthouse-check-action@master
      with:
        urls: 'https://dev.earlman.me/portfolio/moonrise/'